#pragma once

#include "IApp.h"
#include <vector>

#define MAX_APPS_PER_PAGE 9

struct AppEntry {
    const char*      name;
    /* Pre-converted 64×64 RGB565 array (4096 words), flash-resident.
     * Generated by convert_icons.py — zero runtime heap usage. */
    const uint16_t*  icon_rgb565;
    IApp*            app_instance;
};

class App_Grid : public IApp {
private:
    std::vector<AppEntry> apps;
    int selected_index;
    
    float cursor_x;
    float cursor_y;
    float target_cursor_x;
    float target_cursor_y;
    float cursor_vx;
    float cursor_vy;

    float cursor_w;
    float cursor_h;
    float target_cursor_w;
    float target_cursor_h;
    float cursor_vw;
    float cursor_vh;

    float anim_time;

public:
    App_Grid();
    ~App_Grid() override;

    /**
     * @brief Register an application on the launcher grid.
     * @param name        Display label shown when the app is selected.
     * @param icon        Pointer to a 64×64 RGB565 array (4096 uint16_t words).
     *                    Must be flash-resident (generated by convert_icons.py).
     * @param app         Pointer to the IApp implementation (static lifetime).
     */
    void registerApp(const char* name, const uint16_t* icon, IApp* app);

    void init() override;
    void exit() override;
    void loop() override;
    void render(LGFX_Sprite* canvas) override;
    void handleInput(input_event_t event) override;
};
