#include "ui_task.h"
#include "../../include/LGFX_Config.h"
#include "../config/sys_config.h"
#include "../system/sys_mgr.h"
#include "../managers/input_mgr.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_log.h"

#include "apps/IApp.h"
#include "apps/App_Grid.h"
#include "apps/App_OTA.h"
#include "apps/App_Settings.h"
#include "apps/App_Torch.h"
#include "theme_mgr.h"
#include "nvs_flash.h"
#include "nvs.h"

// RGB565 icon arrays — generated by convert_icons.py (pre-build step).
// Each file exposes: static const uint16_t icon_<name>[4096]
#include "../assets/icons/ota.h"
#include "../assets/icons/settings.h"
#include "../assets/icons/torch.h"

static const char *TAG = "UI_TASK";

static LGFX_ESP32S3_ST7735 tft;
static LGFX_Sprite canvas(&tft);

static uint8_t current_brightness = 255;

void ui_set_brightness(uint8_t val) {
    if (val < 10) val = 10;
    current_brightness = val;
    tft.setBrightness(val);
    
    nvs_handle_t handle;
    if (nvs_open("ui_cfg", NVS_READWRITE, &handle) == ESP_OK) {
        nvs_set_u8(handle, "brightness", val);
        nvs_commit(handle);
        nvs_close(handle);
    }
}

uint8_t ui_get_brightness(void) {
    return current_brightness;
}

static App_Grid app_grid;
static App_OTA app_ota;
static App_Settings app_settings;
static App_Torch app_torch;

static IApp* current_app = nullptr;

void switch_to_app(IApp* app) {
    if (current_app) {
        current_app->exit();
    }
    current_app = app;
    if (current_app) {
        current_app->init();
    }
}

void switch_to_grid() {
    switch_to_app(&app_grid);
}

static void ui_task_runner(void *arg) {
    ESP_LOGI(TAG, "UI Task Started (Modular App Grid & Themes)");

    tft.init();
    tft.setRotation(1); // Standard Landscape format
    
    // Attempt to load brightness from NVS
    nvs_handle_t handle;
    if (nvs_open("ui_cfg", NVS_READONLY, &handle) == ESP_OK) {
        nvs_get_u8(handle, "brightness", &current_brightness);
        nvs_close(handle);
    }
    tft.setBrightness(current_brightness);

    // Allocate the large 16-bit display buffer in PSRAM to save internal heap
    canvas.setPsram(true);
    canvas.createSprite(tft.width(), tft.height() + 4);
    canvas.setColorDepth(16);

    // 1. Initialize Global Theme Interpolator
    theme_init();

    // 2. Register apps with pre-converted RGB565 icon arrays (zero runtime decoding).
    //    Arrays are flash-resident 64x64 images; App_Grid downsamples to 32x32 on the stack.
    app_grid.registerApp("OTA System", icon_ota,      &app_ota);
    app_grid.registerApp("Torch",      icon_torch,    &app_torch);
    app_grid.registerApp("Settings",   icon_settings,  &app_settings);

    // Boot to Grid
    switch_to_grid();

    while (1) {
        // - Core Mathematics and Dispatching - //
        
        input_event_t ev = input_mgr_get_event();
        if (ev != BTN_NONE && current_app) {
            current_app->handleInput(ev);
        }

        theme_update(); // Smoothly animates colors across theme switches

        if (current_app) {
            current_app->loop();
        }

        if (current_app) {
            current_app->render(&canvas);
        }

        /* Global UI offset: push everything up by 4px to perfectly align with the bezel */
        canvas.pushSprite(0, -4);

        vTaskDelay(pdMS_TO_TICKS(25)); // Cap frame rate
    }
}

extern "C" void ui_task_init(void) {
    xTaskCreatePinnedToCore(
        ui_task_runner,
        "ui_task",
        8192,
        NULL,
        5,
        NULL,
        1
    );
}
